


# Compose file for Boinc Distributed Computing Project
# https://boinc.berkeley.edu/


version: '3.8'
services:
  boinc:
    image: boinc/client
    volumes:
      - "bonic:/var/lib/boinc"
    environment:
      - BOINC_GUI_RPC_PASSWORD="123"
      - BOINC_CMD_LINE_OPTIONS="--allow_remote_gui_rpc"


volumes:
  bonic:
