


# Compose file for Boinc Distributed Computing Project
# https://boinc.berkeley.edu/


version: '3.8'
services:
  boinc:
    image: boinc/client
    container_name: boinc
    network_mode: host
    pid: host
    volumes:
      - "bonic:/var/lib/boinc"
    environment:
      - BOINC_GUI_RPC_PASSWORD="${BOINC_GUI_RPC_PASSWORD}"
      - BOINC_CMD_LINE_OPTIONS="--allow_remote_gui_rpc"


volumes:
  bonic:
