


# Compose file for Boinc Distributed Computing Project
# https://boinc.berkeley.edu/


version: '3.8'
services:
  boinc:
    image: boinc/client
    container_name: boinc
    restart: always
    network_mode: host
    pid: host
    volumes:
      - "bonic:/var/lib/boinc"
    environment:
      - BOINC_GUI_RPC_PASSWORD="${BOINC_GUI_RPC_PASSWORD}"
      - BOINC_REMOTE_HOST=${BOINC_REMOTE_HOST}
      - TZ=${BOINC_TZ}


volumes:
  bonic:
